# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
fa:
  languageCode: fa
  contentDir: content/fa
  title: "دوره‌های آنلاین سبزیاد"
  params:
    description: "سایت آموزش رایگان به زبان فارسی با تمرکز بر دوره‌های کاربردی"
  menu:
    main:
      - name: درباره
        url: "#about"
        weight: 1
      - name: دوره‌ها
        url: "/course/"
        weight: 2
      - name: وبلاگ
        url: "/post/"
        weight: 3

en:
  languageCode: en-us
  contentDir: content/en
  title: "Sabzyad Online Courses"
  params:
    description: "Free and modern online courses in English"
  menu:
    main:
      - name: About
        url: "#about"
        weight: 1
      - name: Courses
        url: "/course/"
        weight: 2
      - name: Blog
        url: "/post/"
        weight: 3